# Generated by Django 4.0.4 on 2022-05-10 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0003_contato_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='do_usuario',
            field=models.IntegerField(default=None),
        ),
    ]
